// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hero$Blog from "../src/components/layout/Hero.bs.js";
import * as Posts$Blog from "./posts.bs.js";

function Index(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Hero$Blog.make, {
                  title: "Blog",
                  subtitle: "A blog with typed powers"
                }), React.createElement(Posts$Blog.make, { }));
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
